language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-26

licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

matrix:
  include:
  - name: "java/advanced/BannerRecyclerViewExample"
    env: PROJ_DIR="java/advanced/BannerRecyclerViewExample"
  - name: "java/advanced/APIDemo"
    env: PROJ_DIR="java/advanced/APIDemo"
  - name: "java/admob/BannerExample"
    env: PROJ_DIR="java/admob/BannerExample"
  - name: "java/admob/RewardedVideoExample"
    env: PROJ_DIR="java/admob/RewardedVideoExample"
  - name: "java/admob/NativeAdvancedExample"
    env: PROJ_DIR="java/admob/NativeAdvancedExample"
  - name: "java/admob/InterstitialExample"
    env: PROJ_DIR="java/admob/InterstitialExample"
  - name: "java/admanager/BannerExample"
    env: PROJ_DIR="java/admanager/BannerExample"
  - name: "java/admanager/CustomRenderingExample"
    env: PROJ_DIR="java/admanager/CustomRenderingExample"
  - name: "java/admanager/RewardedVideoExample"
    env: PROJ_DIR="java/admanager/RewardedVideoExample"
  - name: "java/admanager/InterstitialExample"
    env: PROJ_DIR="java/admanager/InterstitialExample"
  - name: "kotlin/advanced/APIDemo"
    env: PROJ_DIR="kotlin/advanced/APIDemo"
  - name: "kotlin/admob/BannerExample"
    env: PROJ_DIR="kotlin/admob/BannerExample"
  - name: "kotlin/admob/RewardedVideoExample"
    env: PROJ_DIR="kotlin/admob/RewardedVideoExample"
  - name: "kotlin/admob/NativeAdvancedExample"
    env: PROJ_DIR="kotlin/admob/NativeAdvancedExample"
  - name: "kotlin/admob/InterstitialExample"
    env: PROJ_DIR="kotlin/admob/InterstitialExample"
  - name: "kotlin/admanager/BannerExample"
    env: PROJ_DIR="kotlin/admanager/BannerExample"
  - name: "kotlin/admanager/CustomRenderingExample"
    env: PROJ_DIR="kotlin/admanager/CustomRenderingExample"
  - name: "kotlin/admanager/RewardedVideoExample"
    env: PROJ_DIR="kotlin/admanager/RewardedVideoExample"
  - name: "kotlin/admanager/InterstitialExample"
    env: PROJ_DIR="kotlin/admanager/InterstitialExample"

script:
  - pushd "$PROJ_DIR"
  - ./gradlew build
  - popd  
