name: Build Status

# Step 1: Build on pull-requests or pushes to main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  # Step 2: Build the samples
  build-java:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        regex:
        - "java/advanced/APIDemo"
        - "java/advanced/InlineAdaptiveBannerExample"
        - "java/advanced/RewardedSSVExample"
        - "kotlin/advanced/APIDemo"
        - "kotlin/advanced/InlineAdaptiveBannerExample"
        - "java/admob/AppOpenExample"
        - "java/admob/BannerExample"
        - "java/admob/FullScreenNativeExample"
        - "java/admob/InterstitialExample"
        - "java/admob/NativeAdvancedExample"
        - "java/admob/RewardedInterstitialExample"
        - "java/admob/RewardedVideoExample"
        - "kotlin/admob/AppOpenExample"
        - "kotlin/admob/BannerExample"
        - "kotlin/admob/InterstitialExample"
        - "kotlin/admob/NativeAdvancedExample"
        - "kotlin/admob/RewardedInterstitialExample"
        - "kotlin/admob/RewardedVideoExample"
        - "java/admanager/AppOpenExample"
        - "java/admanager/BannerExample"
        - "java/admanager/InterstitialExample"
        - "java/admanager/NativeAdsExample"
        - "java/admanager/RewardedInterstitialExample"
        - "java/admanager/RewardedVideoExample"
        - "kotlin/admanager/AppOpenExample"
        - "kotlin/admanager/BannerExample"
        - "kotlin/admanager/InterstitialExample"
        - "kotlin/admanager/NativeAdsExample"
        - "kotlin/admanager/RewardedInterstitialExample"
        - "kotlin/admanager/RewardedVideoExample"
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Validate projects
        run: .github/workflows/build/folder-crawler.sh
        shell: bash

      - name: Set commit range (push to the main branch, e.g. merge)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV

      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV

      - name: Build
        run: .github/workflows/build/build.sh
        shell: bash
        env:
          COMMIT_RANGE: ${{ env.COMMIT_RANGE }}
          REGEX: ${{ matrix.regex }}
